name: ganihuhstack

services:
  postgres:
    image: postgres:17-alpine
    container_name: ganihuhstack-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: GanihuhStack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: ganihuhstack-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GanihuhStackDb=Host=postgres;Database=GanihuhStack;Username=postgres;Password=Password123!
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  clientapp:
    build:
      context: ./src/Web/ClientApp
      dockerfile: Dockerfile
    container_name: ganihuhstack-clientapp
    ports:
      - "3000:80"
    depends_on:
      - webapi

volumes:
  postgres_data:
